[theme]
primaryColor = "#147d72"
backgroundColor = "#f7f9f6"
secondaryBackgroundColor = "#eff4f0"
textColor = "#17343b"
font = "sans serif"

[server]
maxUploadSize = 200

[browser]
gatherUsageStats = false
